version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Limit to 10 open pull requests for version updates
    open-pull-requests-limit: 10
    # Add assignees
    assignees:
      - "l1khonr"
    # Labels on pull requests for version updates
    labels:
      - "dependencies"
      - "automerge"
    # Groups
    groups:
      # Group React ecosystem updates together
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      # Group Next.js ecosystem updates
      next:
        patterns:
          - "next"
          - "eslint-config-next"
      # Group Radix UI updates
      radix:
        patterns:
          - "@radix-ui/*"
      # Group AI-related dependencies
      ai-deps:
        patterns:
          - "@ai-sdk/*"
          - "openai"
          - "langchain"
          - "@huggingface/*"
    # Ignore certain dependencies from being updated
    ignore:
      # Ignore major version updates for these packages to ensure stability
      - dependency-name: "@react-spring/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-spring"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Add labels for GitHub Actions updates
    labels:
      - "dependencies"
      - "github-actions"